name: Deploy to Google Cloud Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy ai-text-microservice \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --source=. \
            --entry-point=app \
            --trigger-http \
            --allow-unauthenticated \
            --memory=256MB \
            --timeout=60s \
            --min-instances=0 \
            --max-instances=10 \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }},SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}"
